# Generated by Django 4.1.3 on 2022-11-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
